language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jsw32/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jsw32/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-911735738073"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"